---
authors:
  - Daniel Schwitzgebel
license_file: LICENSE
name: collection
namespace: schwitzd
description: My personal Ansible collection
readme: README.md
repository: https://github.com/Schwitzd/me.ansible_collection
version: "1.0.0"