---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Reload Systemd services
  systemd:
    daemon_reload: yes

- name: Enable Vault service
  systemd:
    name: vault
    enabled: yes

- name: Start Vault service
  systemd:
    name: vault
    state: started